### ISSUE TITLE
BLIP-2 PyTorch error when running VisualWebArena

### ISSUE THREAD

**Issue by xhluca** [ServiceNow/BrowserGym#283] opened 2024-11-29 00:04 UTC
When running VWA, I ran into this error:

```
2024-11-28 18:56:02,966 - 898488 - browsergym.experiments.loop - WARNING - Exception uncaught by agent or environment in task visualwebarena.739.
RuntimeError:
shape mismatch: value tensor of shape [131072] cannot be broadcast to indexing result of shape [65536]
Traceback (most recent call last):
  File "/home/users/username/myproject/venv/lib/python3.10/site-packages/browsergym/experiments/loop.py", line 276, in run
    step_info.from_step(env, action, obs_preprocessor=agent.obs_preprocessor)
  File "/home/users/username/myproject/venv/lib/python3.10/site-packages/browsergym/experiments/loop.py", line 411, in from_step
    self.obs, self.reward, self.terminated, self.truncated, env_info = env.step(action)
  File "/home/users/username/myproject/venv/lib/python3.10/site-packages/gymnasium/wrappers/common.py", line 125, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
  File "/home/users/username/myproject/venv/lib/python3.10/site-packages/gymnasium/wrappers/common.py", line 393, in step
    return super().step(action)
  File "/home/users/username/myproject/venv/lib/python3.10/site-packages/gymnasium/core.py", line 322, in step
    return self.env.step(action)
  File "/home/users/username/myproject/venv/lib/python3.10/site-packages/browsergym/core/env.py", line 433, in step
    reward, done, user_message, task_info = self._task_validate()
  File "/home/users/username/myproject/venv/lib/python3.10/site-packages/browsergym/core/env.py", line 458, in _task_validate
    reward, done, user_message, info = self.task.validate(self.page, self.chat.messages)
  File "/home/users/username/myproject/venv/lib/python3.10/site-packages/browsergym/visualwebarena/task.py", line 283, in validate
    score = self.evaluator(
  File "/home/users/username/myproject/venv/lib/python3.10/site-packages/visualwebarena/evaluation_harness/evaluators.py", line 636, in __call__
    cur_score = evaluator(trajectory, config_file, page)
  File "<@beartype(visualwebarena.evaluation_harness.evaluators.PageImageEvaluator.__call__) at 0x7f95e2e94dc0>", line 92, in __call__
  File "/home/users/username/myproject/venv/lib/python3.10/site-packages/visualwebarena/evaluation_harness/evaluators.py", line 576, in __call__
    pred_ans = self.captioning_fn(
  File "/home/users/username/myproject/venv/lib/python3.10/site-packages/visualwebarena/evaluation_harness/image_utils.py", line 52, in caption_images
    generated_ids = captioning_model.generate(
  File "/home/users/username/myproject/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/users/username/myproject/venv/lib/python3.10/site-packages/transformers/models/blip_2/modeling_blip_2.py", line 2324, in generate
    inputs_embeds[special_image_mask] = language_model_inputs.flatten()
RuntimeError: shape mismatch: value tensor of shape [131072] cannot be broadcast to indexing result of shape [65536]
```

I think it has to do with evaluation. Is that potentially caused by a version mistmatch? or is there some edge case to be handled here?

**Comment by gasse** [comment] 2024-12-09 20:37
@xhluca did you find the cause of this? Have you found a workaround?

**Comment by xhluca** [comment] 2024-12-10 15:59
Unfortunately I did not look into this further. If I find something I will give an update. 

Did you run into a similar error?

**Comment by yousaLING** [comment] 2024-12-12 09:27
Hi, I encountered the same problem in other task. After my search, I found the reason. The reason for this phenomenon is due to version issues with transformers and blip2, you can see for details in https://huggingface.co/Salesforce/blip2-opt-2.7b/discussions/39, updata transformers to 4.47 or .from_pretrained("Salesforce/blip2-opt-2.7b", revision="51572668da0eb669e01a189dc22abe6088589a24"). Hope to help you.

**Comment by gasse** [comment] 2024-12-12 16:09
Thanks @yousaLING !

@xhluca can you try with the latest transformers?
```sh
pip install --upgrade transformers
```

**Comment by gasse** [comment] 2024-12-19 17:10
Closing as this is a transformers issue, and seems resolved with latest release

**Closed by gasse** 2024-12-19 17:10 UTC
Labels: bug

**Comment by xhluca** [comment] 2024-12-19 22:45
perhaps it would be good to pin the version to the latest?
